# Generated by Django 2.2.6 on 2019-11-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
    ]
